#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "notation_parser.y".
#

require 'racc/parser.rb'

require_relative 'lib/notation'

class NotationParser < Racc::Parser

module_eval(<<'...end notation_parser.y/module_eval...', 'notation_parser.y', 33)
  def parse(str)
    @tokens = []
    str = str.strip
    
    until str.empty?
      case str
      when /\A\s+/
        str = $'
      when /\A\d+\.\d+/
        @tokens << [:FLOAT, $&]
        str = $'
      when /\A\d+/
        @tokens << [:INTEGER, $&]
        str = $'
      when /\A≥/
        @tokens << [:GTE, $&]
        str = $'
      when /\A≤/
        @tokens << [:LTE, $&]
        str = $'
      when /\A≠/
        @tokens << [:NEQ, $&]
        str = $'
      when /\A≈/
        @tokens << [:APPROX, $&]
        str = $'
      when /\A√/
        @tokens << [:SQRT, $&]
        str = $'
      when /\A∛/
        @tokens << [:CBRT, $&]
        str = $'
      when /\A∜/
        @tokens << [:FRRT, $&]
        str = $'
      when /\A！/
        @tokens << [:FACT, $&]
        str = $'
      when /\A｜/
        @tokens << [:ABS, $&]
        str = $'
      when /\A>=/
        @tokens << [:GE, $&]
        str = $'
      when /\A<=/
        @tokens << [:LE, $&]
        str = $'
      when /\A./
        @tokens << [$&, $&]
        str = $'
      end
    end
    
    @tokens << [false, false]
    @index = 0
    do_parse
  end

  def next_token
    @tokens[@index].tap { @index += 1 }
  end

...end notation_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     5,    11,    12,    11,    12,    11,    12,     5,    11,    12,
     6,     7,     8,     9,    10,    11,    12,     6,     7,     8,
     9,    10,    11,    12,    14,    15,    16,    17,    18,    19,
    20,    21,    11,    12,    11,    12,    11,    12,    11,    12,
    11,    12,    11,    12,    11,    12,    11,    12,    11,    12,
    13,    28,    37 ]

racc_action_check = [
     0,     6,     6,     7,     7,     8,     8,     5,     9,     9,
     0,     0,     0,     0,     0,     0,     0,     5,     5,     5,
     5,     5,     5,     5,     4,     4,     4,     4,     4,     4,
     4,     4,    10,    10,    14,    14,    15,    15,    16,    16,
    17,    17,    18,    18,    19,    19,    20,    20,    21,    21,
     1,    13,    22 ]

racc_action_pointer = [
    -2,    50,   nil,   nil,    20,     5,   -16,   -14,   -12,    -9,
    15,   nil,   nil,    51,    17,    19,    21,    23,    25,    27,
    29,    31,    49,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -20,   -20,    -1,    -2,    -3,   -20,   -20,   -20,   -20,   -20,
   -20,   -18,   -19,   -20,   -20,   -20,   -20,   -20,   -20,   -20,
   -20,   -20,   -20,   -13,   -14,   -15,   -16,   -17,    38,    -5,
    -6,    -7,    -8,    -9,   -10,   -11,   -12,    -4 ]

racc_goto_table = [
    23,    24,    25,    26,    27,   nil,   nil,   nil,    29,    30,
    31,    32,    33,    34,    35,    36,     1,   nil,   nil,   nil,
   nil,    22 ]

racc_goto_check = [
     4,     4,     4,     4,     4,   nil,   nil,   nil,     4,     4,
     4,     4,     4,     4,     4,     4,     1,   nil,   nil,   nil,
   nil,     1 ]

racc_goto_pointer = [
   nil,    16,   nil,   nil,    -6 ]

racc_goto_default = [
   nil,   nil,     2,     3,     4 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 20, :_reduce_none,
  1, 20, :_reduce_none,
  1, 20, :_reduce_none,
  3, 20, :_reduce_4,
  3, 21, :_reduce_5,
  3, 21, :_reduce_6,
  3, 21, :_reduce_7,
  3, 21, :_reduce_8,
  3, 21, :_reduce_9,
  3, 21, :_reduce_10,
  3, 21, :_reduce_11,
  3, 21, :_reduce_12,
  2, 22, :_reduce_13,
  2, 22, :_reduce_14,
  2, 22, :_reduce_15,
  2, 22, :_reduce_16,
  2, 22, :_reduce_17,
  1, 23, :_reduce_18,
  1, 23, :_reduce_19 ]

racc_reduce_n = 20

racc_shift_n = 38

racc_token_table = {
  false => 0,
  :error => 1,
  "(" => 2,
  ")" => 3,
  :GTE => 4,
  :LTE => 5,
  :NEQ => 6,
  :APPROX => 7,
  ">" => 8,
  "<" => 9,
  :GE => 10,
  :LE => 11,
  :SQRT => 12,
  :CBRT => 13,
  :FRRT => 14,
  :FACT => 15,
  :ABS => 16,
  :INTEGER => 17,
  :FLOAT => 18 }

racc_nt_base = 19

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"(\"",
  "\")\"",
  "GTE",
  "LTE",
  "NEQ",
  "APPROX",
  "\">\"",
  "\"<\"",
  "GE",
  "LE",
  "SQRT",
  "CBRT",
  "FRRT",
  "FACT",
  "ABS",
  "INTEGER",
  "FLOAT",
  "$start",
  "expr",
  "comparison",
  "unary_op",
  "number" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'notation_parser.y', 7)
  def _reduce_4(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 9)
  def _reduce_5(val, _values, result)
     result = ≥(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 10)
  def _reduce_6(val, _values, result)
     result = ≤(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 11)
  def _reduce_7(val, _values, result)
     result = ≠(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 12)
  def _reduce_8(val, _values, result)
     result = ≈(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 13)
  def _reduce_9(val, _values, result)
     result = val[0] > val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 14)
  def _reduce_10(val, _values, result)
     result = val[0] < val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 15)
  def _reduce_11(val, _values, result)
     result = val[0] >= val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 16)
  def _reduce_12(val, _values, result)
     result = val[0] <= val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 18)
  def _reduce_13(val, _values, result)
     result = √(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 19)
  def _reduce_14(val, _values, result)
     result = ∛(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 20)
  def _reduce_15(val, _values, result)
     result = ∜(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 21)
  def _reduce_16(val, _values, result)
     result = ！(val[1].to_i)
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 22)
  def _reduce_17(val, _values, result)
     result = ｜(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 24)
  def _reduce_18(val, _values, result)
     result = val[0].to_i
    result
  end
.,.,

module_eval(<<'.,.,', 'notation_parser.y', 25)
  def _reduce_19(val, _values, result)
     result = val[0].to_f
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class NotationParser


# Example usage:
if __FILE__ == $0
  parser = NotationParser.new
  
  test_cases = [
    "10 ≥ 5",
    "5 ≤ 10", 
    "5 ≠ 3",
    "√ 49",
    "！ 5",
    "∛ 27",
    "∜ 16"
  ]
  
  test_cases.each do |test|
    puts "Testing: #{test}"
    begin
      result = parser.parse(test)
      puts "Result: #{result}"
    rescue => e
      puts "Error: #{e.message}"
    end
    puts
  end
end
